// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { dynamic } from '@/app/api/core/matching/interest/route';
export { GET } from '@/app/api/core/matching/interest/route';
export { POST } from '@/app/api/core/matching/interest/route';
