// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/admin/feature-flags/[key]/route';
export { PATCH } from '../../../../../../../src/app/api/admin/feature-flags/[key]/route';
export { DELETE } from '../../../../../../../src/app/api/admin/feature-flags/[key]/route';
export const dynamic = 'force-dynamic';
