// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/cron/python-internal-worker/route';
export const dynamic = 'force-dynamic';
export const maxDuration = 300;
