// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { PATCH } from '../../../../../../../../../src/app/api/mobile/v1/notifications/[id]/read/route';
export const dynamic = 'force-dynamic';
