// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { POST } from '../../../../../../../../src/app/api/mobile/v1/notifications/mark-all-read/route';
export const dynamic = 'force-dynamic';
