// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { POST } from '../../../../../../../src/app/api/matches/[id]/snooze/route';
export { DELETE } from '../../../../../../../src/app/api/matches/[id]/snooze/route';
