// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { PUT } from '../../../../../../../../src/app/api/organizations/[orgId]/ownership/[ownershipId]/route';
export { DELETE } from '../../../../../../../../src/app/api/organizations/[orgId]/ownership/[ownershipId]/route';
export const dynamic = 'force-dynamic';
