// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../../../src/app/api/mobile/v1/organizations/[orgId]/team/route';
export const dynamic = 'force-dynamic';
