// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../../src/app/api/organizations/[orgId]/structure/[id]/route';
export { PUT } from '../../../../../../../../src/app/api/organizations/[orgId]/structure/[id]/route';
export { DELETE } from '../../../../../../../../src/app/api/organizations/[orgId]/structure/[id]/route';
