// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../src/app/api/goals/route';
export { POST } from '../../../../../src/app/api/goals/route';
export { PATCH } from '../../../../../src/app/api/goals/route';
export { DELETE } from '../../../../../src/app/api/goals/route';
export const dynamic = 'force-dynamic';
