// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/core/matching/matching-profile/route';
export { PUT } from '../../../../../../../src/app/api/core/matching/matching-profile/route';
export const dynamic = 'force-dynamic';
