// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { PATCH } from '../../../../../../../src/app/api/expertise/user-skills/[id]/route';
export { DELETE } from '../../../../../../../src/app/api/expertise/user-skills/[id]/route';
