// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { POST } from '../../../../../../../../src/app/api/mobile/v1/devices/token/route';
export { DELETE } from '../../../../../../../../src/app/api/mobile/v1/devices/token/route';
export const dynamic = 'force-dynamic';
