// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/feedback/sus/check-trigger/route';
export { POST } from '../../../../../../../src/app/api/feedback/sus/check-trigger/route';
export const dynamic = 'force-dynamic';
