// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../../src/app/api/mobile/v1/matching/snooze/route';
export { POST } from '../../../../../../../../src/app/api/mobile/v1/matching/snooze/route';
export { DELETE } from '../../../../../../../../src/app/api/mobile/v1/matching/snooze/route';
export const dynamic = 'force-dynamic';
