// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/projects/[id]/route';
export { PATCH } from '../../../../../../src/app/api/projects/[id]/route';
export { DELETE } from '../../../../../../src/app/api/projects/[id]/route';
