// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/user/consent/route';
export { POST } from '../../../../../../src/app/api/user/consent/route';
export const dynamic = 'force-dynamic';
