// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { POST } from '../../../../../../../../../src/app/api/expertise/verifications/sent/[requestType]/[requestId]/route';
export { DELETE } from '../../../../../../../../../src/app/api/expertise/verifications/sent/[requestType]/[requestId]/route';
