// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/organizations/[orgId]/partnerships/route';
export { POST } from '../../../../../../../src/app/api/organizations/[orgId]/partnerships/route';
