// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/user/account/route';
export { DELETE } from '../../../../../../src/app/api/user/account/route';
export const dynamic = 'force-dynamic';
