// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/match/snooze/route';
export { POST } from '../../../../../../src/app/api/match/snooze/route';
export { DELETE } from '../../../../../../src/app/api/match/snooze/route';
