// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/assignment-templates/[id]/route';
export { PATCH } from '../../../../../../src/app/api/assignment-templates/[id]/route';
