// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/notifications/preferences/route';
export { PATCH } from '../../../../../../src/app/api/notifications/preferences/route';
export const dynamic = 'force-dynamic';
