// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/matching/profile/[id]/route';
export { DELETE } from '../../../../../../../src/app/api/matching/profile/[id]/route';
