// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/profile/snippet/route';
export { POST } from '../../../../../../src/app/api/profile/snippet/route';
export { DELETE } from '../../../../../../src/app/api/profile/snippet/route';
export const dynamic = 'force-dynamic';
