// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/conversations/[conversationId]/messages/route';
export { POST } from '../../../../../../../src/app/api/conversations/[conversationId]/messages/route';
