// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/surveys/sus/prompt/route';
export { POST } from '../../../../../../../src/app/api/surveys/sus/prompt/route';
