// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../src/app/api/notifications/route';
export { POST } from '../../../../../src/app/api/notifications/route';
export const dynamic = 'force-dynamic';
