// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { POST } from '../../../../../../src/app/api/upload/avatar/route';
export { DELETE } from '../../../../../../src/app/api/upload/avatar/route';
