// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { POST } from '../../../../../../../../../src/app/api/org/[id]/matches/[matchId]/review/route';
export const dynamic = 'force-dynamic';
