// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/contracts/[id]/route';
export { PATCH } from '../../../../../../src/app/api/contracts/[id]/route';
export { DELETE } from '../../../../../../src/app/api/contracts/[id]/route';
export const dynamic = 'force-dynamic';
