// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/assignments/[id]/pipeline/route';
export { POST } from '../../../../../../../src/app/api/assignments/[id]/pipeline/route';
export const dynamic = 'force-dynamic';
