// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../../src/app/api/portfolio/org/[slug]/export/route';
export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
