// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/feedback/why-not-shortlisted/route';
export { POST } from '../../../../../../src/app/api/feedback/why-not-shortlisted/route';
