// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/user/privacy-settings/route';
export { POST } from '../../../../../../src/app/api/user/privacy-settings/route';
