// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/verify/custom/[token]/route';
export { POST } from '../../../../../../../src/app/api/verify/custom/[token]/route';
