// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/mobile/v1/messages/route';
export { POST } from '../../../../../../../src/app/api/mobile/v1/messages/route';
export const dynamic = 'force-dynamic';
