// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/analytics/fairness/[assignmentId]/route';
export { POST } from '../../../../../../../src/app/api/analytics/fairness/[assignmentId]/route';
export const dynamic = 'force-dynamic';
