// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/skill-gaps/goals/route';
export { POST } from '../../../../../../src/app/api/skill-gaps/goals/route';
export { PATCH } from '../../../../../../src/app/api/skill-gaps/goals/route';
export const dynamic = 'force-dynamic';
