// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/cron/fairness-note/route';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;
