// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { POST } from '../../../../../../../src/app/api/expertise/cv-import/wizard-extract/route';
export const dynamic = 'force-dynamic';
export const maxDuration = 60;
