// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/cron/fairness-report/route';
export { POST } from '../../../../../../src/app/api/cron/fairness-report/route';
