export type DomainCode = 'U' | 'F' | 'T' | 'L' | 'M' | 'D';

export type CanonicalCandidate = {
  domain: DomainCode;
  catId: number;
  subcatId: number;
  l3Id: number;
  name: string;
  description: string;
  tags: string[];
  source: 'curated' | 'external' | 'telemetry';
  priority: 'mandatory' | 'high' | 'normal';
};

export type AliasCandidate = {
  targetSlug: string;
  alias: string;
  source: 'curated' | 'external' | 'telemetry' | 'manual';
  confidence: number;
};

export const DOMAIN_TO_CAT_ID: Record<DomainCode, number> = {
  U: 1,
  F: 2,
  T: 3,
  L: 4,
  M: 5,
  D: 6,
};

export const CANONICAL_TARGET_COUNTS: Record<DomainCode, number> = {
  U: 170,
  F: 180,
  T: 220,
  L: 170,
  M: 130,
  D: 130,
};

export const LANGUAGE_L3_MAPPING = {
  catId: 4,
  subcatId: 105,
  l3Id: 840,
};

export const EXPANDED_LANGUAGE_TERMS: string[] = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Chinese',
  'Japanese',
  'Korean',
  'Arabic',
  'Hindi',
  'Russian',
  'Swedish',
  'Dutch',
  'Polish',
  'Ukrainian',
  'Turkish',
  'Vietnamese',
  'Thai',
  'Indonesian',
  'Malay',
  'Bengali',
  'Urdu',
  'Persian',
  'Hebrew',
  'Greek',
  'Czech',
  'Romanian',
  'Hungarian',
  'Finnish',
  'Danish',
  'Norwegian',
  'Swahili',
  'Tamil',
  'Telugu',
  'Marathi',
  'Punjabi',
  'Filipino',
  'Serbian',
  'Croatian',
  'Slovak',
  'Slovenian',
  'Bulgarian',
  'Lithuanian',
  'Latvian',
  'Estonian',
  'Icelandic',
  'Catalan',
  'Basque',
  'Galician',
  'Irish',
  'Welsh',
  'Afrikaans',
  'Amharic',
  'Yoruba',
  'Zulu',
  'Somali',
  'Nepali',
  'Sinhala',
  'Khmer',
  'Lao',
  'Burmese',
  'Mongolian',
  'Kazakh',
  'Uzbek',
  'Georgian',
  'Armenian',
  'Albanian',
  'Macedonian',
  'Bosnian',
];

export const MANDATORY_TECH_STACK: Array<{
  name: string;
  catId: number;
  subcatId: number;
  l3Id: number;
  tags: string[];
}> = [
  { name: 'Docker', catId: 3, subcatId: 85, l3Id: 673, tags: ['t', 'containers', 'devops'] },
  {
    name: 'Kubernetes',
    catId: 3,
    subcatId: 85,
    l3Id: 673,
    tags: ['t', 'containers', 'orchestration'],
  },
  { name: 'PostgreSQL', catId: 3, subcatId: 77, l3Id: 609, tags: ['t', 'database', 'sql'] },
  { name: 'MySQL', catId: 3, subcatId: 77, l3Id: 609, tags: ['t', 'database', 'sql'] },
  { name: 'MongoDB', catId: 3, subcatId: 77, l3Id: 610, tags: ['t', 'database', 'nosql'] },
  { name: 'Redis', catId: 3, subcatId: 77, l3Id: 610, tags: ['t', 'database', 'cache'] },
  {
    name: 'Amazon Web Services',
    catId: 3,
    subcatId: 85,
    l3Id: 679,
    tags: ['t', 'cloud', 'aws'],
  },
  { name: 'Microsoft Azure', catId: 3, subcatId: 85, l3Id: 679, tags: ['t', 'cloud', 'azure'] },
  {
    name: 'Google Cloud Platform',
    catId: 3,
    subcatId: 85,
    l3Id: 679,
    tags: ['t', 'cloud', 'gcp'],
  },
  {
    name: 'Terraform infrastructure as code',
    catId: 3,
    subcatId: 86,
    l3Id: 683,
    tags: ['t', 'infra', 'iac'],
  },
  {
    name: 'GitHub Actions',
    catId: 3,
    subcatId: 84,
    l3Id: 665,
    tags: ['t', 'cicd', 'automation'],
  },
  {
    name: 'PHP programming language',
    catId: 3,
    subcatId: 82,
    l3Id: 649,
    tags: ['t', 'language', 'php'],
  },
  {
    name: 'Swift programming language',
    catId: 3,
    subcatId: 82,
    l3Id: 649,
    tags: ['t', 'language', 'swift'],
  },
  {
    name: 'Kotlin programming language',
    catId: 3,
    subcatId: 82,
    l3Id: 649,
    tags: ['t', 'language', 'kotlin'],
  },
  {
    name: 'Go programming language',
    catId: 3,
    subcatId: 82,
    l3Id: 649,
    tags: ['t', 'language', 'golang'],
  },
  {
    name: 'C# programming language',
    catId: 3,
    subcatId: 82,
    l3Id: 649,
    tags: ['t', 'language', 'dotnet'],
  },
];

export const FUTURE_OF_WORK_TERMS: Array<{
  name: string;
  catId: number;
  subcatId: number;
  l3Id: number;
  tags: string[];
}> = [
  {
    name: 'AI literacy',
    catId: 1,
    subcatId: 18,
    l3Id: 140,
    tags: ['u', 'future-of-work', 'ai-literacy'],
  },
  {
    name: 'Analytical thinking',
    catId: 1,
    subcatId: 9,
    l3Id: 66,
    tags: ['u', 'future-of-work', 'analytical-thinking'],
  },
  {
    name: 'Creative thinking',
    catId: 1,
    subcatId: 10,
    l3Id: 73,
    tags: ['u', 'future-of-work', 'creative-thinking'],
  },
  {
    name: 'Technological literacy',
    catId: 1,
    subcatId: 18,
    l3Id: 139,
    tags: ['u', 'future-of-work', 'technology-literacy'],
  },
  {
    name: 'Leadership and social influence',
    catId: 1,
    subcatId: 3,
    l3Id: 17,
    tags: ['u', 'future-of-work', 'leadership'],
  },
  {
    name: 'Talent management',
    catId: 1,
    subcatId: 3,
    l3Id: 24,
    tags: ['u', 'future-of-work', 'talent-management'],
  },
  {
    name: 'Empathy and active listening',
    catId: 1,
    subcatId: 1,
    l3Id: 4,
    tags: ['u', 'future-of-work', 'empathy'],
  },
  {
    name: 'Curiosity and lifelong learning',
    catId: 1,
    subcatId: 12,
    l3Id: 95,
    tags: ['u', 'future-of-work', 'lifelong-learning'],
  },
];

export const DOMAIN_KNOWLEDGE_CURATED: Array<{
  l3Id: number;
  subcatId: number;
  terms: string[];
  tag: string;
}> = [
  {
    l3Id: 1195,
    subcatId: 149,
    tag: 'computer-science',
    terms: [
      'Database transaction isolation',
      'Database replication topologies',
      'Query planner diagnostics',
      'Index selectivity analysis',
      'Data normalization strategy',
      'OLTP workload modeling',
      'OLAP query optimization',
      'Schema migration planning',
      'Data consistency guarantees',
      'Distributed query execution',
      'Storage engine internals',
      'Database failover strategy',
      'High availability database design',
    ],
  },
  {
    l3Id: 1277,
    subcatId: 159,
    tag: 'public-health',
    terms: [
      'Epidemiological surveillance design',
      'Outbreak investigation workflow',
      'Population health stratification',
      'Health equity impact assessment',
      'Community health intervention design',
      'Disease burden estimation',
      'Vaccination program analytics',
      'Health behavior change strategy',
      'Public health risk communication',
      'Health systems resilience planning',
      'Environmental health monitoring',
      'Infectious disease modeling',
      'Non-communicable disease prevention planning',
    ],
  },
  {
    l3Id: 1304,
    subcatId: 162,
    tag: 'policy-analysis',
    terms: [
      'Policy impact forecasting',
      'Regulatory options analysis',
      'Cost benefit policy analysis',
      'Policy implementation evaluation',
      'Legislative risk assessment',
      'Scenario-based policy planning',
      'Stakeholder policy mapping',
      'Public consultation synthesis',
      'Evidence-informed policy design',
      'Policy monitoring framework design',
      'Policy instrument selection',
      'Institutional policy diagnostics',
      'Comparative policy benchmarking',
    ],
  },
  {
    l3Id: 1315,
    subcatId: 164,
    tag: 'corporate-finance',
    terms: [
      'Capital structure optimization',
      'Weighted average cost of capital analysis',
      'Debt covenant risk analysis',
      'Cash flow waterfall modeling',
      'Mergers and acquisitions valuation',
      'Discounted cash flow scenario modeling',
      'Working capital optimization',
      'Treasury liquidity planning',
      'Dividend policy analysis',
      'Funding strategy design',
      'Corporate financing term sheet analysis',
      'Enterprise value bridge analysis',
      'Capital allocation governance',
    ],
  },
  {
    l3Id: 1325,
    subcatId: 165,
    tag: 'law-governance',
    terms: [
      'Data privacy legal interpretation',
      'Administrative law compliance review',
      'Regulatory enforcement risk mapping',
      'Privacy impact assessment governance',
      'Cross-border data transfer governance',
      'Consent management compliance design',
      'Public sector compliance controls',
      'Regulatory filing strategy',
      'Digital rights policy compliance',
      'Records retention legal controls',
      'Data subject rights operations',
      'Regulatory audit response planning',
      'Administrative sanctions mitigation',
    ],
  },
  {
    l3Id: 1335,
    subcatId: 166,
    tag: 'education',
    terms: [
      'Learning pathway design',
      'Instructional sequencing strategy',
      'Adaptive learning design',
      'Assessment validity design',
      'Student engagement analytics',
      'Curriculum coherence review',
      'Learning outcomes measurement',
      'Assessment rubric calibration',
      'Digital pedagogy strategy',
      'Blended learning architecture',
      'Inclusive curriculum design',
      'Competency-based education design',
      'Teacher professional learning systems',
    ],
  },
  {
    l3Id: 1356,
    subcatId: 169,
    tag: 'food-systems',
    terms: [
      'Food safety hazard analysis',
      'Nutritional profile formulation',
      'Food processing quality controls',
      'Shelf-life stability modeling',
      'Food traceability design',
      'Food supply chain resilience',
      'Sensory evaluation methodology',
      'Food packaging compliance',
      'Food microbiology risk controls',
      'Sustainable ingredient strategy',
      'Food waste reduction strategy',
      'Product labeling compliance',
      'Cold chain quality governance',
    ],
  },
  {
    l3Id: 1364,
    subcatId: 170,
    tag: 'energy',
    terms: [
      'Battery storage dispatch strategy',
      'Renewable integration planning',
      'Grid flexibility planning',
      'Power purchase agreement analysis',
      'Energy storage lifecycle analysis',
      'Distributed energy resource coordination',
      'Renewable curtailment mitigation',
      'Microgrid resilience strategy',
      'Grid interconnection requirements',
      'Energy market participation strategy',
      'Storage degradation forecasting',
      'Renewables project bankability analysis',
      'Energy transition portfolio planning',
    ],
  },
  {
    l3Id: 1371,
    subcatId: 171,
    tag: 'transportation',
    terms: [
      'Freight network optimization',
      'Last-mile delivery strategy',
      'Intermodal logistics planning',
      'Route reliability analysis',
      'Fleet utilization optimization',
      'Transport demand forecasting',
      'Customs and trade lane planning',
      'Warehouse to transport synchronization',
      'Freight emissions optimization',
      'Logistics contingency planning',
      'Carrier performance analytics',
      'Supply network risk mapping',
      'Reverse logistics strategy',
    ],
  },
  {
    l3Id: 1388,
    subcatId: 173,
    tag: 'climate',
    terms: [
      'Scope 1 emissions accounting',
      'Scope 2 emissions accounting',
      'Scope 3 emissions accounting',
      'GHG baseline development',
      'Carbon reduction roadmap design',
      'Climate disclosure reporting',
      'Science-based target planning',
      'Product carbon footprint modeling',
      'Supplier emissions engagement',
      'Decarbonization scenario analysis',
      'Climate data quality assurance',
      'Carbon accounting controls design',
      'Net-zero transition planning',
    ],
  },
];

export const CURATED_ALIAS_MAP: AliasCandidate[] = [
  { targetSlug: 'google-cloud-platform', alias: 'GCP', source: 'curated', confidence: 1.0 },
  { targetSlug: 'amazon-web-services', alias: 'AWS', source: 'curated', confidence: 1.0 },
  { targetSlug: 'microsoft-azure', alias: 'Azure cloud', source: 'curated', confidence: 0.96 },
  { targetSlug: 'github-actions', alias: 'gh actions', source: 'curated', confidence: 0.99 },
  { targetSlug: 'github-actions', alias: 'github workflows', source: 'curated', confidence: 0.94 },
  {
    targetSlug: 'terraform-infrastructure-as-code',
    alias: 'iac terraform',
    source: 'curated',
    confidence: 0.97,
  },
  { targetSlug: 'docker', alias: 'docker containerization', source: 'curated', confidence: 0.93 },
  { targetSlug: 'kubernetes', alias: 'k8s', source: 'curated', confidence: 1.0 },
  { targetSlug: 'postgresql', alias: 'postgres', source: 'curated', confidence: 1.0 },
  { targetSlug: 'mysql', alias: 'my sql', source: 'curated', confidence: 0.92 },
  { targetSlug: 'mongodb', alias: 'mongo db', source: 'curated', confidence: 0.97 },
  { targetSlug: 'redis', alias: 'redis cache', source: 'curated', confidence: 0.92 },
  { targetSlug: 'php-programming-language', alias: 'php', source: 'curated', confidence: 1.0 },
  { targetSlug: 'swift-programming-language', alias: 'swift', source: 'curated', confidence: 1.0 },
  {
    targetSlug: 'kotlin-programming-language',
    alias: 'kotlin',
    source: 'curated',
    confidence: 1.0,
  },
  { targetSlug: 'go-programming-language', alias: 'golang', source: 'curated', confidence: 1.0 },
  { targetSlug: 'c-programming-13641', alias: 'C++', source: 'curated', confidence: 1.0 },
  {
    targetSlug: 'c-programming-13641',
    alias: 'C plus plus',
    source: 'curated',
    confidence: 0.99,
  },
  { targetSlug: 'nodejs-runtime', alias: 'NodeJS', source: 'curated', confidence: 0.99 },
  { targetSlug: 'nodejs-runtime', alias: 'Node.js', source: 'curated', confidence: 0.98 },
  {
    targetSlug: 'ai-literacy',
    alias: 'artificial intelligence literacy',
    source: 'curated',
    confidence: 0.98,
  },
  {
    targetSlug: 'curiosity-and-lifelong-learning',
    alias: 'lifelong learning',
    source: 'curated',
    confidence: 0.98,
  },
  {
    targetSlug: 'empathy-and-active-listening',
    alias: 'active listening',
    source: 'curated',
    confidence: 0.95,
  },
  {
    targetSlug: 'leadership-and-social-influence',
    alias: 'social influence',
    source: 'curated',
    confidence: 0.93,
  },
];

export const SEARCH_COVERAGE_REQUIRED_TERMS: string[] = [
  'swedish',
  'ukrainian',
  'kubernetes',
  'docker',
  'postgresql',
  'mysql',
  'mongodb',
  'redis',
  'aws',
  'azure',
  'gcp',
  'terraform',
  'gh actions',
  'php',
  'swift',
  'kotlin',
  'ai literacy',
  'analytical thinking',
  'creative thinking',
  'technological literacy',
  'talent management',
  'lifelong learning',
];

export const ALIAS_STOPWORDS = new Set([
  'a',
  'an',
  'and',
  'or',
  'the',
  'of',
  'to',
  'in',
  'on',
  'for',
  'with',
]);
