/**
 * Fairness Note Generator
 *
 * Generates PDF and Markdown reports for fairness analysis
 * Implements PRD Part 7: Automated fairness reporting
 */

import type { FairnessReport } from '@/lib/analytics/fairness';

// ============================================================================
// MARKDOWN GENERATOR
// ============================================================================

/**
 * Generate Markdown fairness report
 */
export function generateFairnessMarkdown(report: FairnessReport): string {
  const { releaseVersion, generatedAt, overallMetrics, segments, summary, recommendations } =
    report;

  const md: string[] = [];

  // Header
  md.push(`# Fairness Analysis Report`);
  md.push(`**Release:** ${releaseVersion}`);
  md.push(`**Generated:** ${generatedAt.toLocaleString()}`);
  md.push('');
  md.push('---');
  md.push('');

  // Executive Summary
  md.push(`## Executive Summary`);
  md.push('');
  md.push(summary);
  md.push('');

  // Overall Metrics
  md.push(`## Overall Metrics`);
  md.push('');
  md.push(`- **Total Matches Generated:** ${overallMetrics.totalMatches.toLocaleString()}`);
  md.push(`- **Total Introductions:** ${overallMetrics.totalIntroductions.toLocaleString()}`);
  md.push(`- **Total Interviews:** ${overallMetrics.totalInterviews.toLocaleString()}`);
  md.push(`- **Total Contracts:** ${overallMetrics.totalContracts.toLocaleString()}`);
  md.push('');

  if (overallMetrics.totalMatches > 0) {
    const introRate = (overallMetrics.totalIntroductions / overallMetrics.totalMatches) * 100;
    md.push(`- **Overall Introduction Rate:** ${introRate.toFixed(1)}%`);
  }

  md.push('');

  // Segment Analysis
  md.push(`## Segment Analysis`);
  md.push('');

  if (segments.length === 0) {
    md.push('*No segment data available (insufficient opt-in participation)*');
    md.push('');
  } else {
    // Group by segment type
    const byType = segments.reduce(
      (acc, s) => {
        const [type] = s.segment.split(':');
        if (!acc[type]) acc[type] = [];
        acc[type].push(s);
        return acc;
      },
      {} as Record<string, typeof segments>
    );

    for (const [type, segs] of Object.entries(byType)) {
      md.push(`### ${type.charAt(0).toUpperCase() + type.slice(1)}`);
      md.push('');

      md.push('| Segment | Acceptance Rate | Gap | Sample Size | Significant? |');
      md.push('|---------|----------------|-----|-------------|--------------|');

      for (const seg of segs) {
        const [, value] = seg.segment.split(':');
        const gapStr = seg.gap >= 0 ? `+${seg.gap.toFixed(1)}pp` : `${seg.gap.toFixed(1)}pp`;
        const sigStr = seg.significant ? `⚠️ Yes (p=${seg.pValue.toFixed(3)})` : 'No';

        md.push(
          `| ${value} | ${seg.segmentRate.toFixed(1)}% | ${gapStr} | ${seg.sampleSize} | ${sigStr} |`
        );
      }

      md.push('');

      // Note significant gaps
      const significantInType = segs.filter((s) => s.significant);
      if (significantInType.length > 0) {
        md.push(`**⚠️ ${significantInType.length} significant gap(s) detected in ${type}**`);
        md.push('');
      }
    }
  }

  // Recommendations
  md.push(`## Recommendations`);
  md.push('');

  if (recommendations.length === 0) {
    md.push('*No recommendations - fairness metrics are within acceptable ranges*');
  } else {
    recommendations.forEach((rec, i) => {
      md.push(`${i + 1}. ${rec}`);
    });
  }

  md.push('');
  md.push('---');
  md.push('');

  // Methodology
  md.push(`## Methodology`);
  md.push('');
  md.push('- **Statistical Test:** Chi-square test for 2x2 contingency tables');
  md.push('- **Significance Threshold:** p < 0.05');
  md.push('- **Minimum Sample Size:** 10 events per segment');
  md.push('- **Opt-In Only:** Only includes users who opted in to demographic tracking');
  md.push('- **Privacy:** All analysis uses aggregated, anonymized data');
  md.push('');

  // Definitions
  md.push(`## Definitions`);
  md.push('');
  md.push(
    '- **Gap:** Percentage point difference between segment acceptance rate and overall baseline'
  );
  md.push('- **Baseline:** Overall acceptance rate across all segments');
  md.push(
    '- **Acceptance Rate:** Percentage of matches that resulted in introductions (mutual interest)'
  );
  md.push('- **Significant:** Gap is statistically significant (unlikely due to chance, p < 0.05)');
  md.push('');

  // Footer
  md.push('---');
  md.push('');
  md.push("*This report was automatically generated by Proofound's Fairness Analytics system.*");
  md.push('*For questions or concerns, contact the platform team at [email protected]*');

  return md.join('\n');
}

/**
 * Generate plain text summary for email
 */
export function generateFairnessSummary(report: FairnessReport): string {
  const { releaseVersion, summary, segments } = report;

  const significantGaps = segments.filter((s) => s.significant);

  let text = `Fairness Report for ${releaseVersion}\n\n`;
  text += `${summary}\n\n`;

  if (significantGaps.length > 0) {
    text += `Significant Gaps Detected:\n`;
    significantGaps.forEach((gap) => {
      text += `- ${gap.segment}: ${gap.gap >= 0 ? '+' : ''}${gap.gap.toFixed(1)}pp (p=${gap.pValue.toFixed(3)})\n`;
    });
  } else {
    text += `No significant fairness gaps detected. ✓\n`;
  }

  text += `\nView full report in admin dashboard.`;

  return text;
}

/**
 * Generate HTML report for web viewing
 */
export function generateFairnessHTML(report: FairnessReport): string {
  const markdown = generateFairnessMarkdown(report);

  // Simple markdown-to-HTML conversion
  // In production, use a proper markdown library
  let html = markdown
    .replace(/^# (.*$)/gim, '<h1>$1</h1>')
    .replace(/^## (.*$)/gim, '<h2>$1</h2>')
    .replace(/^### (.*$)/gim, '<h3>$1</h3>')
    .replace(/\*\*(.*)\*\*/gim, '<strong>$1</strong>')
    .replace(/\*(.*)\*/gim, '<em>$1</em>')
    .replace(/^---$/gim, '<hr>')
    .replace(/\n\n/g, '</p><p>')
    .replace(/^- (.*$)/gim, '<li>$1</li>');

  // Wrap lists
  html = html.replace(/(<li>.*<\/li>)/gs, '<ul>$1</ul>');

  // Wrap paragraphs
  html = `<div class="fairness-report"><p>${html}</p></div>`;

  // Add CSS
  const css = `
    <style>
      .fairness-report {
        font-family: system-ui, -apple-system, sans-serif;
        max-width: 900px;
        margin: 0 auto;
        padding: 2rem;
        line-height: 1.6;
      }
      .fairness-report h1 {
        color: #1C4D3A;
        border-bottom: 2px solid #E8E6DD;
        padding-bottom: 0.5rem;
      }
      .fairness-report h2 {
        color: #2D3330;
        margin-top: 2rem;
      }
      .fairness-report h3 {
        color: #6B6760;
      }
      .fairness-report table {
        width: 100%;
        border-collapse: collapse;
        margin: 1rem 0;
      }
      .fairness-report th,
      .fairness-report td {
        border: 1px solid #E8E6DD;
        padding: 0.5rem;
        text-align: left;
      }
      .fairness-report th {
        background-color: #F7F6F1;
        font-weight: 600;
      }
      .fairness-report ul {
        margin: 1rem 0;
      }
      .fairness-report li {
        margin: 0.5rem 0;
      }
      .fairness-report hr {
        border: none;
        border-top: 1px solid #E8E6DD;
        margin: 2rem 0;
      }
    </style>
  `;

  return css + html;
}

/**
 * Generate CSV export of segment data
 */
export function generateFairnessCSV(report: FairnessReport): string {
  const { segments } = report;

  const rows: string[] = [];

  // Header
  rows.push(
    'Segment,Metric Type,Baseline (%),Segment Rate (%),Gap (pp),P-Value,Significant,Sample Size'
  );

  // Data rows
  for (const seg of segments) {
    rows.push(
      [
        seg.segment,
        seg.metricType,
        seg.baseline.toFixed(2),
        seg.segmentRate.toFixed(2),
        seg.gap.toFixed(2),
        seg.pValue.toFixed(4),
        seg.significant ? 'Yes' : 'No',
        seg.sampleSize.toString(),
      ].join(',')
    );
  }

  return rows.join('\n');
}
