// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../../src/app/api/expertise/user-skills/[id]/verification-request/route';
export { POST } from '../../../../../../../../src/app/api/expertise/user-skills/[id]/verification-request/route';
