// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { PUT } from '../../../../../../../../src/app/api/organizations/[orgId]/goals/[id]/route';
export { DELETE } from '../../../../../../../../src/app/api/organizations/[orgId]/goals/[id]/route';
