// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/assignments/[id]/route';
export { PUT } from '../../../../../../src/app/api/assignments/[id]/route';
export { DELETE } from '../../../../../../src/app/api/assignments/[id]/route';
export const dynamic = 'force-dynamic';
