-- Placeholder migration file for remote version 20251104140610 (create_dashboard_layouts_and_apply_updates).
--
-- This repo did not contain the original SQL for this version when synchronized.
-- The canonical applied history lives in supabase_migrations.schema_migrations on the remote database.
--
-- If you need to recreate this migration precisely, recover it from the original source of migrations,
-- or generate a baseline schema migration after the history is aligned.
