// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../../../src/app/api/mobile/v1/admin/moderation/queue/route';
export const dynamic = 'force-dynamic';
