// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../../src/app/api/expertise/verifications/custom/[requestId]/route';
export { PATCH } from '../../../../../../../../src/app/api/expertise/verifications/custom/[requestId]/route';
