// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../../src/app/api/core/matching/interest/route';
export { POST } from '../../../../../../../src/app/api/core/matching/interest/route';
export const dynamic = 'force-dynamic';
