// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/organizations/[orgId]/route';
export { PUT } from '../../../../../../src/app/api/organizations/[orgId]/route';
