// Auto-generated by scripts/generate-api-app-wrappers.mjs
export { GET } from '../../../../../../src/app/api/expertise/profile/route';
export { PUT } from '../../../../../../src/app/api/expertise/profile/route';
export const dynamic = 'force-dynamic';
