import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

/**
 * POST /api/organizations/[orgId]/evidence-pack
 * 
 * Generate Evidence Pack PDF for organization impact data
 */
export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ orgId: string }> }
) {
  try {
    const { orgId } = await params;
    const supabase = await createClient();

    // Verify user has access
    const {
      data: { user },
    } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Check membership
    const { data: membership } = await supabase
      .from('organization_members')
      .select('role')
      .eq('org_id', orgId)
      .eq('user_id', user.id)
      .single();

    if (!membership) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 });
    }

    // Fetch organization data
    const { data: org, error } = await supabase
      .from('organizations')
      .select('*')
      .eq('id', orgId)
      .single();

    if (error || !org) {
      return NextResponse.json({ error: 'Organization not found' }, { status: 404 });
    }

    // Build HTML for PDF
    const impactEntries = (org.impact_entries as any[]) || [];

    const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${org.display_name} - Evidence Pack</title>
  <style>
    body {
      font-family: 'Crimson Pro', Georgia, serif;
      line-height: 1.6;
      color: #2C3E2C;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
    }
    h1 {
      color: #5C8B89;
      font-size: 32px;
      margin-bottom: 10px;
    }
    h2 {
      color: #7A9278;
      font-size: 24px;
      margin-top: 40px;
      margin-bottom: 20px;
      border-bottom: 2px solid #D4A574;
      padding-bottom: 10px;
    }
    h3 {
      color: #2C3E2C;
      font-size: 18px;
      margin-top: 30px;
      margin-bottom: 15px;
    }
    p {
      margin-bottom: 15px;
    }
    .meta {
      color: #666;
      font-size: 14px;
      margin-bottom: 30px;
    }
    .impact-entry {
      margin-bottom: 40px;
      padding: 20px;
      background: #F9F9F9;
      border-left: 4px solid #5C8B89;
    }
    .metrics-grid {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 15px;
      margin-top: 20px;
    }
    .metric {
      padding: 15px;
      background: white;
      border: 1px solid #ddd;
      border-radius: 4px;
    }
    .metric-name {
      font-size: 12px;
      color: #666;
      margin-bottom: 5px;
    }
    .metric-value {
      font-size: 24px;
      font-weight: bold;
      color: #2C3E2C;
    }
    .metric-unit {
      font-size: 14px;
      color: #666;
    }
    .footer {
      margin-top: 60px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      font-size: 12px;
      color: #666;
      text-align: center;
    }
  </style>
</head>
<body>
  <h1>${org.display_name}</h1>
  <p class="meta">Evidence Pack · Generated ${new Date().toLocaleDateString()}</p>

  ${org.mission ? `
  <h2>Mission</h2>
  <p>${org.mission}</p>
  ` : ''}

  ${org.vision ? `
  <h2>Vision</h2>
  <p>${org.vision}</p>
  ` : ''}

  <h2>Impact Summary</h2>
  <p>This Evidence Pack documents ${impactEntries.length} impact ${impactEntries.length === 1 ? 'entry' : 'entries'} demonstrating measurable outcomes and organizational effectiveness.</p>

  ${impactEntries.length === 0 ? '<p><em>No impact entries recorded yet.</em></p>' : ''}

  ${impactEntries.map((entry: any, index: number) => `
    <div class="impact-entry">
      <h3>${index + 1}. ${entry.title}</h3>
      <p><strong>Timeframe:</strong> ${entry.timeframe}</p>
      ${entry.beneficiaries ? `<p><strong>Beneficiaries:</strong> ${entry.beneficiaries}</p>` : ''}
      <p>${entry.description}</p>
      
      ${entry.metrics && entry.metrics.length > 0 ? `
        <div class="metrics-grid">
          ${entry.metrics.map((metric: any) => `
            <div class="metric">
              <div class="metric-name">${metric.name}</div>
              <div class="metric-value">${metric.value} <span class="metric-unit">${metric.unit}</span></div>
            </div>
          `).join('')}
        </div>
      ` : ''}
    </div>
  `).join('')}

  <div class="footer">
    <p>Generated by Proofound · ${org.display_name}</p>
    ${org.website ? `<p>${org.website}</p>` : ''}
  </div>
</body>
</html>
    `;

    // For now, return HTML that can be converted to PDF on the client side
    // In production, you'd use a library like puppeteer or a service like DocRaptor
    // For this implementation, we'll return HTML and let the browser handle it
    
    const blob = new Blob([html], { type: 'text/html' });

    return new NextResponse(blob, {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${org.slug}-evidence-pack-${new Date().toISOString().split('T')[0]}.html"`,
      },
    });
  } catch (error) {
    console.error('Error generating evidence pack:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

